# -*- coding: utf-8 -*-
"""009-01 Check Affiliates in 2 files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6P1SQXRNnd2xyOfZ6GupD3QAMFf1pIM
"""

import pandas as pd

# Load files
ar_file = pd.read_excel('AR.xlsx', sheet_name='Tracking Codes')
a_file = pd.read_excel('A.xlsx', sheet_name='sheet')

# Compare the columns in 2 files
only_in_ar = ar_file[~ar_file['AffiliateID'].isin(a_file['Affiliate ID'])]
only_in_a = a_file[~a_file['Affiliate ID'].isin(ar_file['AffiliateID'])]

# Display the results
print('Only in AR:')
print(only_in_ar)

print('Only in A:')
print(only_in_a)

# Save the results to a new excel file
with pd.ExcelWriter('affiliate_id_comparison.xlsx') as writer:
    only_in_ar.to_excel(writer, sheet_name='Only in AR', index=False)
    only_in_a.to_excel(writer, sheet_name='Only in A', index=False)

import pandas as pd

# Load files
ar_file = pd.read_excel('AR.xlsx', sheet_name='Tracking Codes')
a_file = pd.read_excel('A.xlsx', sheet_name='sheet')

# Compare the columns in 2 files
only_in_ar = ar_file[~ar_file['AffiliateID'].isin(a_file['Affiliate ID'])]
only_in_a = a_file[~a_file['Affiliate ID'].isin(ar_file['AffiliateID'])]

# Display the results
print('Only in AR:')
print(only_in_ar)

print('Only in A:')
print(only_in_a)

# Save the results to a new excel file
with pd.ExcelWriter('comparasion.xlsx') as writer:
    only_in_ar.to_excel(writer, sheet_name='Only in AR')
    only_in_a.to_excel(writer, sheet_name='Only in A')

import pandas as pd

# load data
ar = pd.read_excel('AR.xlsx', sheet_name='Tracking Codes')
a = pd.read_excel('A.xlsx', sheet_name='sheet')

# compare
in_ar = ar[~ar['AffiliateID'].isin(a['Affiliate ID'])]
in_a = a[~a['Affiliate ID'].isin(ar['AffiliateID'])]

# display
print('Only in AR:')
print(in_ar)

print('Only in A:')
print(in_a)

# save
with pd.ExcelWriter('comparasion.xlsx') as writer:
    in_ar.to_excel(writer, sheet_name='Only in AR')
    in_a.to_excel(writer, sheet_name='Only in A')